#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# 	"bad luck from china" for the 4th iteration
#	"bad luck from Japan" for the 9th iteration
#	"bad luck from Italy" for the 17th iteration

count=1
while [ $count -le 20 ]
do
	echo "$count"
	(( count++ ))

	case "$count" in
		"5") echo "bad luck from China"
		;;
		"10") echo "bad luck from Japan"
		;;
		"18") echo "bad luck from italy"
		;;

	esac
done
