#!/usr/bin/env bash
#comment

count=1
while [ $count -lt 21 ]
do
	echo "$count"
	(( count++ ))

	case "$count" in
		"5") echo "bad luck from China"
		;;
		"10") echo "bad luck from Japan"
		;;
		"18") echo "bad luck from italy"
		;;

	esac
done
